name: Streamlit Cloud Compatibility

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify_compatibility:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-github.txt ]; then pip install -r requirements-github.txt; fi
    - name: Verify Streamlit compatibility
      run: |
        # Check that main.py exists and contains streamlit imports
        if ! grep -q "import streamlit" main.py; then
          echo "Error: main.py does not import streamlit"
          exit 1
        fi
        # Validate that required directories exist
        for dir in scidiscover resources; do
          if [ ! -d "$dir" ]; then
            echo "Error: Required directory $dir not found"
            exit 1
          fi
        done
        echo "✅ Streamlit Cloud compatibility verified"